# Generated by Django 5.2.4 on 2025-11-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='audiosample',
            name='file',
            field=models.FileField(max_length=255, upload_to='music_samples/'),
        ),
        migrations.AlterField(
            model_name='filmproject',
            name='poster_image',
            field=models.ImageField(max_length=255, upload_to='film_posters/'),
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='album_cover',
            field=models.ImageField(max_length=255, upload_to='music_covers/'),
        ),
    ]
